### ISSUE TITLE
Can't find RxSwift version

### ISSUE THREAD

**Issue by vBoykoGit** [LucasVanDongen/iOSArchitecturesCompared#2]
I want to compare rxSwift version

**Comment by LucasVanDongen** [comment]
I was planning to do a Combine / SwiftUI rewrite somewhere and blog again about the differences and experience when I have time, but it's hard to find that time. I have been using ReactiveKit in a lot of projects which is similar in approach to RxSwift and I like it so I'm looking forward to see it in a native solution in the form of Combine.

But I can tell without even trying that it would have made this architecture somewhat more easy to accomplish since it's all about passing signals. So instead of using those delegates you would simply subscribe to the right PassthroughSubject to consume the messages and updates:

`somePassthroughSubject.filter { $0.chatId == self.chatId }.observeNext { /* update the UI */ } `

There is 0 chance I'm going to update the project to RxSwift since the future I need to invest in is Combine.

**Comment by vBoykoGit** [comment]
Okay, i understand combine/swiftUI is better, but i want to compare RxSwift ViewModel vs Your Static ViewModel.

**Comment by LucasVanDongen** [comment]
Sorry it's been a while I worked on this project, indeed there's a mentioning of an RxSwift version but that one was never built due to time constraints. If you share example code with other developers it needs to be _perfect_ not _almost perfect_ and perfect costs a lot of time. Sorry I'm really not in the capacity of doing that anymore. I've updated the README.
